CURRENT_GPU: 0
TRAIN_STEP_ADD: False
DATASET:
    NAME: "gdal_landcover_common"
    ROOT_PATH: /data_zs/data/sandong_dataset #/dataset/data/sandong_dataset #/data_zs/data/sandong_dataset
    MEAN: [0.5, 0.5, 0.5] #[0.29310304, 0.2636692, 0.20883968, 0.39742813]  #[0.5, 0.5, 0.5]
    STD:  [0.5, 0.5, 0.5] #[0.09101917, 0.09300123, 0.106814794, 0.1142725]       #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 3 #4
    NUM_CLASSES: 6
    CLASS_INDEX: [{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5}]   #[0, 255]
    IGNORE_INDEX: 255

TRAIN:
    EPOCHS: 200
    CROP_SIZE: 256 #(512, 512)
    BATCH_SIZE: 16 #12_2080ti_2  32_3090_11G_1.5   16_2080ti_2  16_b2_3090_15G_s2
    GRAD_STEPS: 1
    MODEL_SCALE: 2
    DATA_LIST: /data_zs/data/sandong_dataset/train/split.csv #/dataset/data/sandong_dataset/train/split.csv #/data_zs/data/sandong_dataset/train/split.csv
    FOLD: 0
    DATA_AUGMENT: train_transform
    BACKBONE_PRETRAINED_PATH: /data_zs/data/pretrained_models/mit_b1.pth #/data_zs/data/pretrained_models/mit_b1.pth #/dataset/data/pretrained_models/mit_b1.pth #
    PRETRAINED_MODEL_PATH:  #/dataset/rsipac_runs/semi_stage/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-10-25-08-51/best_checkpoint.pth.tar
    AMP: True
VAL:
    BATCH_SIZE: 24 #12   24_2080ti_2
    CROP_SIZE: 256 #512 #(512, 512)
    DATA_LIST: /data_zs/data/sandong_dataset/train/split.csv #/dataset/data/sandong_dataset/train/split.csv #/data_zs/data/sandong_dataset/train/split.csv #/workspace/dataset/rsipac_semi_val_list_6000_b3.txt #/dataset/config/rsipac/select5985_val_from_rsipac_semi_full_35000_remain_random.txt #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/train/GID15_train_list_subset_balance.txt
TEST:
    BATCH_SIZE: 6
    CROP_SIZE: #512 #(512, 512)
    TEST_MODEL_PATH: #/data_zs/output/sandong_runs/checkpoint/sandong_segformer_b1_ce_dice_512_fold0-515_0119/best_checkpoint.pth.tar #/workspace/runs/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b1_gdal_landcover_common_2021-10-17-13-00/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b5_gdal_landcover_common_2021-10-06-08-00/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/best_0.66343_68.11_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-10-03-14-14/best_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-10-02-11-41/98_0.66089_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-09-28-01-30/59_0.66541_checkpoint.pth.tar #/dataset/rsipac_runs/checkpoints/SegFormer_mit_b3_gdal_landcover_common_2021-09-25-11-32/120_0.66107_checkpoint.pth.tar
    USE_TTA: False

SOLVER:
    OPTIMIZER: "poly_adamw"
    LR_SCHEDULER: poly #'one_cylcle' #poly #cosine  one_cylcle
    LR: 6e-5
    LOSS_NAME: dice_sce_contrast_loss #ohem_ce_loss_v2 #ce_focal_diceloss #ce_focal_diceloss #ce_focalloss #dice_sce_contrast_loss #ce_loss #imagebase_CEloss #focal_diceloss #"pixelcontrast"

MODEL:
    SOURCE: #"smp"
    MODEL_NAME: "SegFormer" #"Unet"
    BACKBONE: "mit_b1" #"efficientnet-b3"
    ACTIVATION: #"sigmoid"

VISUAL:
    LOG_SAVE_DIR: /dataset/output/sandong_runs/logs #/dataset/output/sandong_runs/logs #/data_zs/output/sandong_runs/logs #/code/python/pytorch/runs/logs
    MODEL_SAVE_DIR: /dataset/output/sandong_runs/checkpoint #/dataset/output/sandong_runs/checkpoint #/data_zs/output/sandong_runs/checkpoint #/code/python/pytorch/runs/checkpoints
    OUTPUT_DIR: /dataset/output/sandong_runs/visual #/dataset/output/sandong_runs/visual #/data_zs/output/sandong_runs/visual
    CURRENT_NAME: sandong_segformer_b1_dice_sce_contrast_fold0-515_0121_scale2_ep200
UTILS:
    VAL_START: 0 #62 #62
    EPOCH_STOP: 200 #66 #67
