CURRENT_GPU: 1
DATASET:
    NAME: "gdal_landcover_common"
    ROOT_PATH: /data_zs/GID_RGB_15_512x512_0overlap_sub #/data/datasets/GID_RGB_15_1024x1024 #J:\Expert_Datasets\GreenLand_3band_512x512_2numclass
    DATA_LIST: #/data/open_datasets/GID_RGB_15_512x512_0overlap_sub/trainGID15_label.p
    MEAN: [0.3729486, 0.38768908, 0.35791704] # [0.3539229, 0.3734769, 0.34095916]  #  [0.5, 0.5, 0.5]
    STD:  [0.24537781, 0.23425555, 0.23242144] # [0.23289922, 0.22774169, 0.22549641] #     #[0.5, 0.5, 0.5]
    NUM_CHANNELS: 3
    NUM_CLASSES: 16
    CLASS_INDEX: [[0, 0, 0],
                  [200, 0, 0],
                  [250, 0, 150],
                  [200, 150, 150],
                  [250, 150, 150],
                  [0, 200, 0],
                  [150, 250, 0],
                  [150, 200, 150],
                  [200, 0, 200],
                  [150, 0, 250],
                  [150, 150, 250],
                  [250, 200, 0],
                  [200, 200, 0],
                  [0,   0, 200],
                  [0,   150, 200],
                  [0,   200, 250]]   #[0, 255]
    IGNORE_INDEX: -1
TRAIN:
    EPOCHS: 200
    CROP_SIZE: 512 #(512, 512)
    BATCH_SIZE: 6
    BACKBONE_PRETRAINED_PATH: /data_zs/code/pytorchAI_segmentation_landcover_transfer/pretrain_pth/hrnetv2_w18_imagenet_pretrained.pth #/code/python/pytorch/pytorchAI_segmentation_GID/pretrain_pth/hrnet-w18-small-v1-08f8ae64.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth #/data/code/pytorchAI_segmentation/pretrain_pth/efficientnet-b3-5fb5a3c3.pth
    LOG_SAVE_DIR: ../runs/logs
    MODEL_SAVE_DIR: ../runs/checkpoints
TEST:
    BATCH_SIZE: 8
    CROP_SIZE: #512 #(512, 512)
    TEST_MODEL_PATH: #/code/python/pytorch/runs/checkpoints/Unet_efficientnet-b3_gdal_landcover_2021-07-14-08-29/15_0.50232_checkpoint.pth.tar #../trained_models/hrnet_w18_small_v1_cityscapes_cls19_1024x2048_trainset_segmentron.pth

SOLVER:
    OPTIMIZER: "sgd"
    LR: 0.01
    LOSS_NAME: #imagebase_CEloss #focal_diceloss #"pixelcontrast"
MODEL:
    SOURCE: #"smp"
    MODEL_NAME: "HRNet_OCR" #"HRNet" #"Unet"
    BACKBONE: "hrnet_w18_small" #"efficientnet-b7"
    ACTIVATION: #"sigmoid"
    HRNET:
        FINAL_CONV_KERNEL: 1
        STAGE1:
            NUM_MODULES: 1
            NUM_BRANCHES: 1
            BLOCK: BOTTLENECK
            NUM_BLOCKS:
                - 2
            NUM_CHANNELS:
                - 64
            FUSE_METHOD: SUM
        STAGE2:
            NUM_MODULES: 1
            NUM_BRANCHES: 2
            BLOCK: BASIC
            NUM_BLOCKS:
                - 2
                - 2
            NUM_CHANNELS:
                - 18
                - 36
            FUSE_METHOD: SUM
        STAGE3:
            NUM_MODULES: 3
            NUM_BRANCHES: 3
            BLOCK: BASIC
            NUM_BLOCKS:
                - 2
                - 2
                - 2
            NUM_CHANNELS:
                - 18
                - 36
                - 72
            FUSE_METHOD: SUM
        STAGE4:
            NUM_MODULES: 2
            NUM_BRANCHES: 4
            BLOCK: BASIC
            NUM_BLOCKS:
                - 2
                - 2
                - 2
                - 2
            NUM_CHANNELS:
                - 18
                - 36
                - 72
                - 144
            FUSE_METHOD: SUM
